export const API_ENDPOINTS = {
  LOGIN: "/login",
  REGISTER: "/register",
  LOGOUT: "/logout",
  FORGET_PASSWORD: "/forget-password",
  CATEGORIES: "/category",
  FEATURED_CATEGORIES: "/featured_categories.json",
  COLLECTIONS: "/collections",
  BRANDS: "/collections/filters",
  FILTERS: "/collections/filters",
  PRODUCTS: "/products.json",
  FEATURED_PRODUCTS: "/featured_products.json",
  // TOP_SELLER_PRODUCTS: "/products_top_seller.json",
  TOP_SELLER_PRODUCTS: "/products/topSeller",
  ON_SELLING_PRODUCTS: "/products_on_selling.json",
  PRODUCT: "/products",
  USER: "/user",
  ADD_ADDRESS: "/user/address",
  SINGLE_PRODUCT: "/products/detail",
  RELATED_PRODUCTS: "/related_products.json",
  BEST_SELLER_PRODUCTS: "/products/topSeller",
  NEW_ARRIVAL_PRODUCTS: "/products_new_arrival.json",
  FLASH_SALE_PRODUCTS: "/protectivegear",
  SHOPS: "/shops.json",
  SHOP: "/shop.json",
  SEARCH: "/search.json",
  ORDERS: "/orders.json",
  ORDER: "/orders",
  ADD_ORDER: "/orders/add",
};
